run:
  dir: .
sweep:
  dir: .
  subdir: .
output_subdir: null

job:
  chdir: False
  env_set:
    WANDB_START_METHOD: thread
    WANDB_DIR: ${oc.env:LOGGING_DIR}

job_logging:
  disable_existing_loggers: true

hydra_logging:
  disable_existing_loggers: true

runtime:
  version: "1.3"
  version_base: "1.2"