defaults:
  - data: default
  - logger: default
  - model: baby_realbasic
  - optimizer: adam
  - scheduler: cosine

metric:
  _target_: core.metrics.MetricCollection
  metrics:
    PSNR:
      _target_: piqa.PSNR
    SSIM:
      _target_: piqa.SSIM

seed_index: null

ddp: True
max_epochs: 5000000
gradient_clip_val: 1
num_grad_acc: 1

restore: null
from_lightning: False