# reproducibility
seed_index: 0
deterministic: False

trainer:
  devices: 1
  accelerator: cpu
  precision: bf16-mixed
  max_epochs: 1
  accumulate_grad_batches: 1
  num_sanity_val_steps: 2
  gradient_clip_val: 10.0
  val_check_interval: 1.0
  deterministic: ${train.deterministic}

restore:
  ckpt_or_run_path: null

monitor:
  metric: 'loss/val'
  mode: 'min'

callbacks:
  - _target_: pytorch_lightning.callbacks.EarlyStopping

  - _target_: pytorch_lightning.callbacks.ModelCheckpoint

logger:
  _target_: pytorch_lightning.loggers.WandbLogger