# reproducibility
seed_index: 0
deterministic: False

restore: null

ddp: False

monitor:
  metric: 'loss/val'
  mode: 'min'

defaults:
  - trainer: default
  - callbacks: default
  - logger: default
  - strategy: default

