_target_: pytorch_lightning.loggers.WandbLogger #core.loggers.WandbLogger
project: ${core.project_name}
save_dir: ${oc.env:LOGGING_DIR}
run_id: ${core.run_id}
name: ${core.run_name}
tags: ${core.tags}