# reproducibility
seed_index: 0
deterministic: False

trainer:
  devices: 1
  accelerator: gpu
  precision: 16-mixed
  max_epochs: 1500
  max_steps: 100000
  accumulate_grad_batches: 4
  num_sanity_val_steps: 2
  deterministic: ${train.deterministic}
  strategy: null #deepspeed_stage_3_offload

restore:
  ckpt_path: null

monitor:
  metric: 'loss/val'
  mode: 'min'

callbacks:
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    patience: 1000
    verbose: False
    monitor: ${train.monitor.metric}
    mode: ${train.monitor.mode}

  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    save_top_k: 1
    verbose: False
    monitor: ${train.monitor.metric}
    mode: ${train.monitor.mode}
    save_last: True

  - _target_: pytorch_lightning.callbacks.ModelSummary

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: ${core.project_name}
  save_dir: ${oc.env:LOGGING_DIR}
  tags: ${core.tags}