generator:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${train.trainer.max_steps}
  eta_min: 5e-5
  verbose: False

discriminator:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${train.trainer.max_steps}
  eta_min: 1e-4
  verbose: False