generator:
  _target_: torch.optim.lr_scheduler.ChainedScheduler
  schedulers:
    - _target_: torch.optim.lr_scheduler.LinearLR
      start_factor: 1e-15
      total_iters: 750

    - _target_: torch.optim.lr_scheduler.CosineAnnealingLR
      T_max: ${train.trainer.max_steps}
      eta_min: 3e-5


discriminator:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${train.trainer.max_steps}
  eta_min: 1e-4
  verbose: False