generator: &defaults
  _target_: core.schedulers.CosineAnnealingLinearWarmup
  first_cycle_steps: 2000
  cycle_mult: 1.0
  min_lrs_pow: 2
  warmup_steps: 500
  gamma: 0.8

discriminator:
  _target_: core.schedulers.CosineAnnealingLinearWarmup
  first_cycle_steps: 2000
  cycle_mult: 1.0
  min_lrs_pow: 2
  warmup_steps: 500
  gamma: 0.8