generator:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${train.trainer.max_steps}
  eta_min: ${nn.module.optimizer.generator.lr}
  verbose: False

discriminator:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${train.trainer.max_steps}
  eta_min: ${nn.module.optimizer.generator.lr}
  verbose: False