generator:
  _target_: torch.optim.lr_scheduler.LinearLR
  start_factor: 1e-20
  total_iters: 750

discriminator:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 500000
  eta_min: 1e-4
  verbose: False