generator:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 200000
  eta_min: 1e-6
  verbose: False

discriminator:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: 1000000
  eta_min: 2e-4
  verbose: False