generator:
  _target_: torch.optim.Adam
  lr: 5e-5
  betas: [ 0.9, 0.99 ]
  eps: 1e-08
  weight_decay: 0

discriminator:
  _target_: torch.optim.Adam
  lr: 1e-4
  betas: [ 0.9, 0.99 ]
  eps: 1e-08
  weight_decay: 0