_target_: moe.MoEVRT.deepspeed.vrt_moe.TinyVRT
upscale: ${train.data.datasets.train.scale}
in_chans: 3
out_chans: 3
refine_ch: 64
refine_blocks: 5
refine_steps: 3
img_size: [ 6, 64, 64 ]
window_size: [ 6, 8, 8 ]
depths: [ 4, 4, 4, 4, 4, 4, 4 ]
indep_reconsts: [ -2, -1 ]
embed_dims: [ 32, 32, 32, 32, 32, 32, 32 ]
num_heads: [ 4, 4, 4, 4, 4, 4, 4 ]
num_experts: 2
num_gpus: 2
top_k: 2
mul_attn_ratio: 0.75
mlp_ratio: 2.
qkv_bias: True
qk_scale: null
drop_path_rate: 0.2
optical_flow_pretrained: True
pa_frames: 2
deformable_groups: 4
