_target_: vsrlab.vsr.models.RealBasicVSR.realbasicvsr.RealBasicVSR
cleaning_blocks: 20
mid_channels: 64
upscale: ${train.data.datasets.train.scale}
res_blocks: 20
pretrained_flow: true
train_flow: False