_target_: vsr.models.RealBasicVSR.moerealbasic.RealBasicVSR
cleaning_blocks: 5
mid_channels: 64
upscale: ${train.data.datasets.train.scale}
is_mirror: False
res_blocks: 5
num_experts: 4
top_k: 2
num_gpus: 1
deformable_groups: 4
pretrained_flow: true
train_flow: false