_target_: vsrlab.vsr.models.VRT.spyvrt.SPyVRT
upscale: ${train.data.datasets.train.scale}
in_chans: 3
out_chans: 3
refine_steps: 3
refine_blocks: 5
refine_ch: 64
img_size: [ 6, 64, 64 ]
window_size: [ 6, 8, 8 ]
depths: [ 4, 4, 4, 4, 4, 4, 4 ]
indep_reconsts: [ -2, -1 ]
embed_dims: [ 32, 32, 32, 32, 32, 32, 32 ]
num_heads: [ 4, 4, 4, 4, 4, 4, 4 ]
mul_attn_ratio: 0.75
mlp_ratio: 2.
qkv_bias: True
qk_scale: null
drop_path_rate: 0.2
k: 5
optical_flow_pretrained: "/home/aghinassi/Desktop/nn-lab/storage/video-super-resolution/kjhsdvqqqqq/checkpoint/4.ckpt"
return_levels: [ 2, 3, 4 ]
optical_flow_train: False
pa_frames: 2
deformable_groups: 4