# reproducibility
seed_index: 0
deterministic: False

restore:
  ckpt_path: '/home/Desktop/nn-lab/storage/video-super-resolution/zx3b62ya/checkpoints/last.ckpt'

monitor:
  metric: 'loss/val'
  mode: 'min'

strategy:
  _target_: pytorch_lightning.strategies.DeepSpeedStrategy
  stage: 3
  load_full_weights: True

defaults:
  - trainer: default
  - callbacks: default
  - logger: default