# reproducibility
seed_index: 0
deterministic: False

restore:
  ckpt_path: "cd Desktop/nn-lab/storage/video-super-resolution/zx3b62ya/checkpoints/last.ckpt/checkpoint/zero_pp_rank_1_mp_rank_00_model_states.pt"

monitor:
  metric: 'loss/val'
  mode: 'min'

strategy:
  _target_: pytorch_lightning.strategies.DeepSpeedStrategy
  stage: 3
  load_full_weights: True
  offload_optimizer: cpu

defaults:
  - trainer: default
  - callbacks: default
  - logger: default