# reproducibility
seed_index: 0
deterministic: False

restore:
  ckpt_path: "/home/aghinassi/Desktop/nn-lab/storage/video-super-resolution/ltkflmx0/checkpoints/best.ckpt/latest"

monitor:
  metric: 'loss/val'
  mode: 'min'

strategy:
  _target_: pytorch_lightning.strategies.DeepSpeedStrategy
  stage: 3
  offload_optimizer: cpu

defaults:
  - trainer: default
  - callbacks: default
  - logger: default
