# reproducibility
seed_index: 0
deterministic: False

restore:
  ckpt_path: null

monitor:
  metric: 'loss/val'
  mode: 'min'

strategy:
  _target_: pytorch_lightning.strategies.DeepSpeedStrategy
  stage: 3
  load_full_weights: True
  offload_optimizer: cpu

defaults:
  - trainer: default
  - callbacks: default
  - logger: default
