core:
  project_name: 'video-super-resolution'
  storage_dir: ${oc.env:PROJECT_ROOT}/core
  version: 0.0.1
  tags: null

defaults:
  - hydra: default.yaml
  - nn: mixervsr_pretrain.yaml
  - train: mixervsr_pretrain.yaml
  - _self_