core:
  project_name: 'video-super-resolution'
  run_id: 'baby_rbvsr_gan'
  run_name: "Baby Real Basic - Finetune"
  storage_dir: ${oc.env:LOGGING_DIR}
  version: 0.0.1
  tags: null

defaults:
  - hydra: default
  - nn: default
  - train: default
  - override nn/module: gan
  - override nn/module/optimizer: deepspeed
  - override train/trainer: deepspeed
  - override train/strategy: deepspeed
  - _self_