core:
  project_name: 'video-super-resolution'
  run_id: 'default'
  storage_dir: ${oc.env:LOGGING_DIR}
  version: 0.0.1
  tags: null

defaults:
  - hydra: default
  - nn: default
  - train: default
  - _self_