_target_: vsr.models.MixerVSR.mixervsr.MixerVSR
img_size: [ 64, 64 ]
mid_ch: 64
it_blocks: 20
patch_size: 8
time_dim: ${nn.data.datasets.train.seq}
exp: 2
mix_blocks: 20
conv_blocks: 20
upscale: ${nn.data.datasets.train.scale}