_target_: vsr.models.VRT.vrt.TinyVRT
in_chans: 3
out_chans: 3
refine_steps: 3
refine_blocks: 5
refine_ch: 64
img_size: [6, 64, 64]
window_size: [6, 8, 8]
depths: [6, 6, 6, 6, 6, 4, 4]
indep_reconsts: [-2, -1]
embed_dims: [40, 40, 40, 40, 40, 80, 80]
num_heads: [4, 4, 4, 4, 4, 4, 4]
mul_attn_ratio: 0.75
mlp_ratio: 2.
qkv_bias: True
qk_scale: null
drop_path_rate: 0.2
optical_flow_pretrained: True
pa_frames: 2
deformable_groups: 4
restore_hidden: 64
restore_layers: 5
