_target_: vsr.pl_module.pl_module.LitFlowVSR
log_interval: 250
filter_params: True
reverse: True

teacher:
  _target_: optical_flow.modules.spynet.Spynet
  pretrained: ${oc.env:PROJECT_ROOT}/src/optical_flow/weights/pretrained_spynet.pth

set_lr:
  groups:
    - "spynet"
  lrs:
    - 1e-5

metric:
  _target_: core.metrics.MetricCollection
  metrics:
    PSNR:
      _target_: piqa.PSNR

    SSIM:
      _target_: piqa.SSIM

defaults:
  - model: baby_realbasic
  - loss: pixel_loss
  - optimizer: adam
  - scheduler: cosine_warmup