_target_: vsr.models.RealBasicVSR.pl_module.GanLit
log_interval: 250

d_step_frequency: 1

set_lr: null

d_set_lr: null

metric:
  _target_: core.metrics.MetricCollection
  metrics:
    PSNR:
      _target_: piqa.PSNR

    SSIM:
      _target_: piqa.SSIM

discriminator:
  _target_: vsr.models.RealBasicVSR.modules.unet-discriminator.UNetDiscriminator
  in_ch: 3
  mid_ch: 64

perceptual_loss:
  _target_: core.losses.PerceptualLoss
  weight: 1.0

adversarial_loss:
  _target_: core.losses.AdversarialLoss
  weight: 5e-2

defaults:
  - model: baby_realbasic
  - loss: pixel_loss
  - optimizer: gan_adam
  - scheduler: gan_cosine