- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  save_top_k: 3
  verbose: False
  monitor: ${train.monitor.metric}
  mode: ${train.monitor.mode}
  save_last: True

- _target_: pytorch_lightning.callbacks.LearningRateMonitor
  logging_interval: step

