run:
  dir: .
sweep:
  dir: .
  subdir: .
output_subdir: null

job:
  chdir: False
  env_set:
    WANDB_START_METHOD: thread
    WANDB_DIR: ${oc.env:LOGGING_DIR}

defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

runtime:
  version: "1.3"
  version_base: "1.2"