- _target_: pytorch_lightning.callbacks.ModelCheckpoint
  save_top_k: 1
  filename: "best"
  verbose: False
  monitor: ${train.monitor.metric}
  mode: ${train.monitor.mode}
  save_last: True

- _target_: pytorch_lightning.callbacks.ModelSummary
  max_depth: 3