_target_: pytorch_lightning.strategies.DeepSpeedStrategy
stage: 3
offload_optimizer: cpu
allgather_bucket_size: 100000
reduce_bucket_size: 100000
partition_activations: True
cpu_checkpointing: True
contiguous_memory_optimization: True